# Configure profiles for customizing dotfiles
title = "config.toml"

[settings]
projects = ['zsh','p10k']
files.zsh = ['.zshrc']

[profile]

[profile.home]
zsh_path = '/opt/homebrew/bin:/Users/danturkel/.local/bin:/Users/danturkel/go/bin'
aliases = ''

[profile.hinge]
# system dirs (/usr/local/bin, /usr/bin, ...) are already on PATH
zsh_path = '/Users/danturkel/.local/bin:/Users/danturkel/go/bin'
aliases = """
source ~/.zshrc-extra
alias rp='cd ~/repos/'
"""
